services:
  php:
    build:
      context: .
      dockerfile: .docker/prod/php/8.4/Dockerfile
    volumes:
      - .:/var/www/html:rw
    expose:
      - "9000"
    environment:
      - NETTE_DEBUG=1

  nginx:
    image: nginx:latest
    ports:
      - "8085:80"
    volumes:
      - ./.docker/prod/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html:z
    depends_on:
      - php

